version: '3.7'

services: 
  post-service: 
    image: anthonyvestsage/post-service:latest
    container_name: post-service
    working_dir: /app
    build:
        context: ./posts
        dockerfile: develop.Dockerfile
    ports:
        - 4000:4000

  comments-service: 
    image: anthonyvestsage/comments-service:latest
    container_name: comments-service
    working_dir: /app
    build:
        context: ./comments
        dockerfile: develop.Dockerfile
    ports:
        - 4001:4001

  query-service: 
    image: anthonyvestsage/query-service:latest
    container_name: query-service
    working_dir: /app
    build:
        context: ./query
        dockerfile: develop.Dockerfile
    ports:
        - 4002:4002

  moderation-service: 
    image: anthonyvestsage/moderation-service:latest
    container_name: moderation-service
    working_dir: /app
    build:
        context: ./moderation
        dockerfile: develop.Dockerfile
    ports:
        - 4003:4003

  event-bus-service: 
    image: anthonyvestsage/event-bus-service:latest
    container_name: event-bus-service
    working_dir: /app
    build:
        context: ./event-bus
        dockerfile: develop.Dockerfile
    ports:
        - 4005:4005
