version: '3.7'

services: 
  post-service: 
    image: anthonyvestsage/post-service:latest
    container_name: post-service
    working_dir: /app
    build:
        context: .
        dockerfile: posts/develop.Dockerfile
    ports:
        - 4000:4000

  comments-service: 
    image: comments-service:latest
    container_name: comments-service
    working_dir: /app
    build:
        context: .
        dockerfile: comments/develop.Dockerfile
    ports:
        - 4001:4001

  query-service: 
    image: query-service:latest
    container_name: query-service
    working_dir: /app
    build:
        context: .
        dockerfile: query/develop.Dockerfile
    ports:
        - 4002:4002

  moderation-service: 
    image: moderation-service:latest
    container_name: moderation-service
    working_dir: /app
    build:
        context: .
        dockerfile: moderation/develop.Dockerfile
    ports:
        - 4003:4003

  event-bus-service: 
    image: event-bus-service:latest
    container_name: event-bus-service
    working_dir: /app
    build:
        context: .
        dockerfile: event-bus/develop.Dockerfile
    ports:
        - 4005:4005
